### ISSUE TITLE
add a tool to update all required nodejs versions

### ISSUE THREAD

**Issue by Idrinth** [idrinth-api-bench/issues#198]
**Is your feature request related to a problem? Please describe.**
Currently nodejs version have to be added manually, see #118 , making it likely, that it may be forgotten in one of the currently 5 package.json files, that are included in the project.

**Describe the solution you'd like**
create a tool in the root project, that updates all engine level restrictions to the current two nodejs versions. The version must only be a major version(i.e. 21 not 21.1) and the tool must automatically handle additional example projects without codechanges. The version should be provided via prompt.

**Comment by Idrinth** [comment]
- fs module for filesystem operation
- JSON to handle the json
- prompt to ask for version
- use tools/publish.js for inspiration

**Comment by Selmy44** [comment]
I'm currently working on this task

**Comment by Idrinth** [comment]
no longer possible
