### ISSUE TITLE
Add a tools used page under /contributing

### ISSUE THREAD

**Issue by Idrinth** [idrinth-api-bench/issues#420]
## Context

The website currently gives little insight into what we are using to provide the framework and all related tools.

## Solution

Provide a list of technologies/frameworks used with a short description where they are used. There should be a link back to the respective repositories.

**Comment by stephviz** [comment]
reminder: Description tool logo name

**Comment by Idrinth** [comment]
The big ones are:

- typescript: basis language used
- react: documentation website
- svelte: history website
- fastify: history microservice
- docker: prebuild 
- eslint: every project part
- chai: every project part
- mocha: every project part
- cypress: websites
- stylelint: websites

**Comment by stephviz** [comment]
find links for the above via their github

**Comment by Idrinth** [comment]
new tool:
- markmap-render: mindmap

**Comment by Idrinth** [comment]
new tools:
- vue: desktop
- elektron: desktop
- express: website-builder
