### ISSUE TITLE
Create website builder

### ISSUE THREAD

**Issue by Idrinth** [idrinth-api-bench/issues#851]
## Is your feature request related to a problem? Please describe

Right now we are building both the documentation website and the mindmap every ten minutes. This is a waste of time and resource in most cases.

## Describe the solution you'd like

We need to split the build process in multiple parts, to achieve that we need a service reacting to a webhook push even and a schedule:

- on push to master build mindmap
  - make sure files in `mindmap` were actually changed
  - `git pull`
  - maximum once every 5 mins build
  - use `npm run build`
  - deploy `dist` to target folder (config)
- on push to master build documentation-website
  - make sure files in  `documentation-website` were actually changed
  - maximum once every 10 mins build
  - use `npm run contributor-build`
  - deploy `dist` to target folder (configurable)
- if there has been no full `documentation-website` build for 10 minutes
  - build documentation website
  - use `npm run build`
  - deploy `dist` to target folder(configurable)

## Additional context

Event to listen for: https://docs.github.com/en/webhooks/webhook-events-and-payloads#push
Pulling: https://git-scm.com/docs/git-pull
Diffing a pull: https://git-scm.com/docs/git-diff

**Comment by Idrinth** [comment]
> I will attempt this.

Thank you!

**Comment by hussainnaqvee** [comment]
I would like to work on the issue.

**Comment by Idrinth** [comment]
https://github.com/idrinth-api-bench/website-builder is the new repo for this :) @BarakMShalom and @hussainnaqvee - not sure who of you wants to take over?

**Comment by BarakMShalom** [comment]
> https://github.com/idrinth-api-bench/website-builder is the new repo for this :) @BarakMShalom and @hussainnaqvee - not sure who of you wants to take over?

Hi, unfortunately I am under a lot of stress with other matters at the moment so I don't know when I will be able to approach this issue. Apologies for any inconvenience.

**Comment by Idrinth** [comment]
> > https://github.com/idrinth-api-bench/website-builder is the new repo for this :) @BarakMShalom and @hussainnaqvee - not sure who of you wants to take over?
> 
> Hi, unfortunately I am under a lot of stress with other matters at the moment so I don't know when I will be able to approach this issue. Apologies for any inconvenience.

then @hussainnaqvee feel free to take over for now, well find something new and fresh once you have time again @BarakMShalom :)

**Comment by hussainnaqvee** [comment]
@Idrinth can you review the latest changes if you're free?

**Comment by Idrinth** [comment]
> @Idrinth can you review the latest changes if you're free?

terribly sorry, must have overlooked that notification
